version: '3'

services:
  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth
    ports:
      - '3000:3000'
    depends_on:
      - user-postgres-db
      - rabbitmq
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run start:dev auth

  book:
    build:
      context: ./
      dockerfile: ./apps/book/Dockerfile
    container_name: book
    ports:
      - '3001:3001'
    depends_on:
      - book-postgres-db
      - rabbitmq
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run start:dev book

  offer:
    build:
      context: ./
      dockerfile: ./apps/offer/Dockerfile
    container_name: offer
    ports:
      - '3002:3002'
    depends_on:
      - offer-postgres-db
      - rabbitmq
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run start:dev offer

  search:
    build:
      context: ./
      dockerfile: ./apps/search/Dockerfile
    container_name: search
    ports:
      - '3003:3003'
    depends_on:
      - rabbitmq
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run start:dev search

  user:
    build:
      context: ./
      dockerfile: ./apps/user/Dockerfile
    container_name: user
    ports:
      - '3004:3004'
    depends_on:
      - user-postgres-db
      - rabbitmq
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run start:dev user

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - '5672:5672'

  book-postgres-db:
    image: postgres
    restart: always
    container_name: book-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - '5432:5432'
    volumes:
      - ./db/book/data:/var/lib/postgresql/data

  offer-postgres-db:
    image: postgres
    restart: always
    container_name: offer-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
      PGPORT: 5433
    ports:
      - '5433:5433'
    volumes:
      - ./db/offer/data:/var/lib/postgresql/data

  user-postgres-db:
    image: postgres
    restart: always
    container_name: user-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
      PGPORT: 5434
    ports:
      - '5434:5434'
    volumes:
      - ./db/user/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  nginx:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - auth
      - book
      - offer
      - search
      - user
    ports:
      - 8080:80
